server:
  port: 8085

spring:
  application:
    name: foo-service
    
#  boot:
#    admin:
#      url: http://localhost:9999
#      username: admin
#      password: password
#      client:
#        metadata:
#          user.name: ${security.user.name}
#          user.password: ${security.user.password}

#security:
#  user:
#    name: baz
#    password: password
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8098/eureka/
management:
  security:
    enabled: false    
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka:password@localhost:8098/eureka/
#    
#    
