server:
  port: 9999
spring:
  application:
    name: spring-boot-admin
  profiles:
    active:
    - insecure
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@192.168.86.56:8098/eureka/

security:
  user:
    name: admin
    password: password